spring:
  cloud:
    nacos:
      discovery:
        metadata:
          preserved.register.source: SPRING_CLOUD
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

robot:
  api:
    connect-timeout: 5000
    read-timeout: 10000
    max-retries: 3
    retry-interval: 1000
    base-url: http://localhost:8080/api
  redis:
    command-expire-minutes: 5
    result-expire-minutes: 5
  rate-limit:
    enabled: true
    qps: 100
    max-queueing-time-ms: 500
    warm-up-period-sec: 10
    max-waiting-time: 1000
    resource-name: robot-api
    command-limit-per-minute: 100
    limit-mode: REJECT 